name: opentracing
version: 1.0.6
description: This library is the Open Tracing API written in Dart. It is intended for use both on the server and in the browser.
homepage: http://opentracing.io/

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  meta: ^1.2.2

dev_dependencies:
  build_runner: '>=1.7.1 <3.0.0'
  build_test: ">=0.10.9 <2.0.0"
  build_web_compilers: ^2.5.1
  test: ^1.15.7
